server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bobo?useSSL=false&serverTimezone=UTC
    username: root
    password: zhao635481603
#配置mybatis
mybatis:
  mapper-locations: classpath:com/bobo/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#sql语句日志打印
logging:
  level:
    com:
      mashibing:
        mapper: debug
